### ISSUE TITLE
Set Full Width of Header Items

### ISSUE THREAD

**Issue by dewebey** [MPowerKit/TabView#1]
Hi,
I tried several ways to set the FullWidth of the tabs, but It doesn't work.

E.g. using a FlexLayout has no effect:

`<tabview:TabView.HeaderItemsLayout>
    <FlexLayout JustifyContent="SpaceAround" HorizontalOptions="FillAndExpand" Grid.Row="0" BackgroundColor="BurlyWood" />
</tabview:TabView.HeaderItemsLayout>`

**Comment by Alex-Dobrynin** [comment]
Hi, sorry for so late response. Lost notification about this issue.

What do you mean under FullWidth? provide more info, that i can properly understand your needs

**Comment by dewebey** [comment]
Hi Alex,
I mean something like this:

![image](https://github.com/MPowerKit/TabView/assets/7867557/823c81cb-bf91-4224-bbc9-5c69e0653e29)

**Comment by Alex-Dobrynin** [comment]
Just use grid with star column definitions as HeaderItemsLayout.
